// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjoJaWWJNRZWUhfeC-iqPpmwWMjxmrAnQ',
    appId: '1:301743914382:web:e93559b54650b26e78f8df',
    messagingSenderId: '301743914382',
    projectId: 'unic-connect',
    authDomain: 'unic-connect.firebaseapp.com',
    storageBucket: 'unic-connect.firebasestorage.app',
    measurementId: 'G-3LCJ0J5P0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAxT-XKDPf0bSL5iqyUcghI55WUfIBNUI',
    appId: '1:301743914382:android:ee10882056d6a24a78f8df',
    messagingSenderId: '301743914382',
    projectId: 'unic-connect',
    storageBucket: 'unic-connect.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvW_s_4UndcB6c2zn3egHvFvM6iHxy68',
    appId: '1:301743914382:ios:dd318466405ea78278f8df',
    messagingSenderId: '301743914382',
    projectId: 'unic-connect',
    storageBucket: 'unic-connect.firebasestorage.app',
    iosClientId: '301743914382-n6q5gn41is6p8no8mv1s3kg0ao2bc48n.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjoJaWWJNRZWUhfeC-iqPpmwWMjxmrAnQ',
    appId: '1:301743914382:web:08406172c9bfaf0078f8df',
    messagingSenderId: '301743914382',
    projectId: 'unic-connect',
    authDomain: 'unic-connect.firebaseapp.com',
    storageBucket: 'unic-connect.firebasestorage.app',
    measurementId: 'G-1N1JPW9VPD',
  );

}